

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Паспортные_данныеItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Паспортные_данныеItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Паспортные_данныеItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Паспортные_данныеItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Паспортные_данныеItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Паспортные_данныеItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Паспортные_данныеItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Личный_Номер
        {
            get
            {
                return global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Личный_Номер);
            }
            set
            {
                global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Личный_Номер, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Личный_Номер_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Личный_Номер_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Личный_Номер_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Данные_паспорта_серия
        {
            get
            {
                return global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Данные_паспорта_серия);
            }
            set
            {
                global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Данные_паспорта_серия, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_паспорта_серия_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_паспорта_серия_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_паспорта_серия_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Данные_паспорта_номер
        {
            get
            {
                return global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Данные_паспорта_номер);
            }
            set
            {
                global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Данные_паспорта_номер, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_паспорта_номер_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_паспорта_номер_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_паспорта_номер_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> Данные_паспорта_дата_выдачи
        {
            get
            {
                return global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Данные_паспорта_дата_выдачи);
            }
            set
            {
                global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Данные_паспорта_дата_выдачи, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_паспорта_дата_выдачи_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_паспорта_дата_выдачи_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_паспорта_дата_выдачи_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Данные_паспорта_кем_выдан
        {
            get
            {
                return global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Данные_паспорта_кем_выдан);
            }
            set
            {
                global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Данные_паспорта_кем_выдан, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_паспорта_кем_выдан_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_паспорта_кем_выдан_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_паспорта_кем_выдан_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Персональные_данныеItem Персональные_данныеItem
        {
            get
            {
                return global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Персональные_данныеItem);
            }
            set
            {
                global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItem_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Паспортные_данныеItem,
                global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass,
                global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Личный_Номер;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass>.Entry
                __Паспортные_данныеItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.__Паспортные_данныеItem_CreateNew,
                    global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.__Паспортные_данныеItem_Created,
                    global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.__Паспортные_данныеItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Паспортные_данныеItem __Паспортные_данныеItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Паспортные_данныеItem> es)
            {
                return new global::LightSwitchApplication.Паспортные_данныеItem(es);
            }
            private static void __Паспортные_данныеItem_Created(global::LightSwitchApplication.Паспортные_данныеItem e)
            {
                e.Паспортные_данныеItem_Created();
            }
            private static bool __Паспортные_данныеItem_AllowSaveWithErrors(global::LightSwitchApplication.Паспортные_данныеItem e)
            {
                bool result = false;
                e.Паспортные_данныеItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, int> Личный_Номер
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Личный_Номер) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<int>> Данные_паспорта_серия
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Данные_паспорта_серия) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<int>> Данные_паспорта_номер
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Данные_паспорта_номер) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<global::System.DateTime>> Данные_паспорта_дата_выдачи
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Данные_паспорта_дата_выдачи) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, string> Данные_паспорта_кем_выдан
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Данные_паспорта_кем_выдан) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem> Персональные_данныеItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Персональные_данныеItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Личный_Номер { get; set; }
                new global::System.Nullable<int> Данные_паспорта_серия { get; set; }
                new global::System.Nullable<int> Данные_паспорта_номер { get; set; }
                new global::System.Nullable<global::System.DateTime> Данные_паспорта_дата_выдачи { get; set; }
                new string Данные_паспорта_кем_выдан { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Персональные_данныеItem { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, int>.Entry
                    Личный_Номер = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, int>.Entry(
                        "Личный_Номер",
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Личный_Номер_Stub,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Личный_Номер_ComputeIsReadOnly,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Личный_Номер_Validate,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Личный_Номер_GetImplementationValue,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Личный_Номер_SetImplementationValue,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Личный_Номер_OnValueChanged);
                private static void _Личный_Номер_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Личный_Номер, sf);
                }
                private static bool _Личный_Номер_ComputeIsReadOnly(global::LightSwitchApplication.Паспортные_данныеItem e)
                {
                    bool result = false;
                    e.Личный_Номер_IsReadOnly(ref result);
                    return result;
                }
                private static void _Личный_Номер_Validate(global::LightSwitchApplication.Паспортные_данныеItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Личный_Номер_Validate(r);
                }
                private static int _Личный_Номер_GetImplementationValue(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Личный_Номер;
                }
                private static void _Личный_Номер_SetImplementationValue(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Личный_Номер = v;
                }
                private static void _Личный_Номер_OnValueChanged(global::LightSwitchApplication.Паспортные_данныеItem e)
                {
                    e.Личный_Номер_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<int>>.Entry
                    Данные_паспорта_серия = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Данные_паспорта_серия",
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_серия_Stub,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_серия_ComputeIsReadOnly,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_серия_Validate,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_серия_GetImplementationValue,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_серия_SetImplementationValue,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_серия_OnValueChanged);
                private static void _Данные_паспорта_серия_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Данные_паспорта_серия, sf);
                }
                private static bool _Данные_паспорта_серия_ComputeIsReadOnly(global::LightSwitchApplication.Паспортные_данныеItem e)
                {
                    bool result = false;
                    e.Данные_паспорта_серия_IsReadOnly(ref result);
                    return result;
                }
                private static void _Данные_паспорта_серия_Validate(global::LightSwitchApplication.Паспортные_данныеItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Данные_паспорта_серия_Validate(r);
                }
                private static global::System.Nullable<int> _Данные_паспорта_серия_GetImplementationValue(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Данные_паспорта_серия;
                }
                private static void _Данные_паспорта_серия_SetImplementationValue(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Данные_паспорта_серия = v;
                }
                private static void _Данные_паспорта_серия_OnValueChanged(global::LightSwitchApplication.Паспортные_данныеItem e)
                {
                    e.Данные_паспорта_серия_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<int>>.Entry
                    Данные_паспорта_номер = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Данные_паспорта_номер",
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_номер_Stub,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_номер_ComputeIsReadOnly,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_номер_Validate,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_номер_GetImplementationValue,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_номер_SetImplementationValue,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_номер_OnValueChanged);
                private static void _Данные_паспорта_номер_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Данные_паспорта_номер, sf);
                }
                private static bool _Данные_паспорта_номер_ComputeIsReadOnly(global::LightSwitchApplication.Паспортные_данныеItem e)
                {
                    bool result = false;
                    e.Данные_паспорта_номер_IsReadOnly(ref result);
                    return result;
                }
                private static void _Данные_паспорта_номер_Validate(global::LightSwitchApplication.Паспортные_данныеItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Данные_паспорта_номер_Validate(r);
                }
                private static global::System.Nullable<int> _Данные_паспорта_номер_GetImplementationValue(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Данные_паспорта_номер;
                }
                private static void _Данные_паспорта_номер_SetImplementationValue(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Данные_паспорта_номер = v;
                }
                private static void _Данные_паспорта_номер_OnValueChanged(global::LightSwitchApplication.Паспортные_данныеItem e)
                {
                    e.Данные_паспорта_номер_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    Данные_паспорта_дата_выдачи = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "Данные_паспорта_дата_выдачи",
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_дата_выдачи_Stub,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_дата_выдачи_ComputeIsReadOnly,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_дата_выдачи_Validate,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_дата_выдачи_GetImplementationValue,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_дата_выдачи_SetImplementationValue,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_дата_выдачи_OnValueChanged);
                private static void _Данные_паспорта_дата_выдачи_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Данные_паспорта_дата_выдачи, sf);
                }
                private static bool _Данные_паспорта_дата_выдачи_ComputeIsReadOnly(global::LightSwitchApplication.Паспортные_данныеItem e)
                {
                    bool result = false;
                    e.Данные_паспорта_дата_выдачи_IsReadOnly(ref result);
                    return result;
                }
                private static void _Данные_паспорта_дата_выдачи_Validate(global::LightSwitchApplication.Паспортные_данныеItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Данные_паспорта_дата_выдачи_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _Данные_паспорта_дата_выдачи_GetImplementationValue(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Данные_паспорта_дата_выдачи;
                }
                private static void _Данные_паспорта_дата_выдачи_SetImplementationValue(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.Данные_паспорта_дата_выдачи = global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _Данные_паспорта_дата_выдачи_OnValueChanged(global::LightSwitchApplication.Паспортные_данныеItem e)
                {
                    e.Данные_паспорта_дата_выдачи_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, string>.Entry
                    Данные_паспорта_кем_выдан = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, string>.Entry(
                        "Данные_паспорта_кем_выдан",
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_кем_выдан_Stub,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_кем_выдан_ComputeIsReadOnly,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_кем_выдан_Validate,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_кем_выдан_GetImplementationValue,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_кем_выдан_SetImplementationValue,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Данные_паспорта_кем_выдан_OnValueChanged);
                private static void _Данные_паспорта_кем_выдан_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Данные_паспорта_кем_выдан, sf);
                }
                private static bool _Данные_паспорта_кем_выдан_ComputeIsReadOnly(global::LightSwitchApplication.Паспортные_данныеItem e)
                {
                    bool result = false;
                    e.Данные_паспорта_кем_выдан_IsReadOnly(ref result);
                    return result;
                }
                private static void _Данные_паспорта_кем_выдан_Validate(global::LightSwitchApplication.Паспортные_данныеItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Данные_паспорта_кем_выдан_Validate(r);
                }
                private static string _Данные_паспорта_кем_выдан_GetImplementationValue(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Данные_паспорта_кем_выдан;
                }
                private static void _Данные_паспорта_кем_выдан_SetImplementationValue(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Данные_паспорта_кем_выдан = v;
                }
                private static void _Данные_паспорта_кем_выдан_OnValueChanged(global::LightSwitchApplication.Паспортные_данныеItem e)
                {
                    e.Данные_паспорта_кем_выдан_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Entry
                    Персональные_данныеItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Entry(
                        "Персональные_данныеItem",
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_Stub,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_Validate,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_GetImplementationValue,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_SetImplementationValue,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_Refresh,
                        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_OnValueChanged);
                private static void _Персональные_данныеItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Data> c, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Персональные_данныеItem, sf);
                }
                private static bool _Персональные_данныеItem_ComputeIsReadOnly(global::LightSwitchApplication.Паспортные_данныеItem e)
                {
                    bool result = false;
                    e.Персональные_данныеItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _Персональные_данныеItem_Validate(global::LightSwitchApplication.Паспортные_данныеItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Персональные_данныеItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Персональные_данныеItem_GetCoreImplementationValue(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Персональные_данныеItem;
                }
                private static global::LightSwitchApplication.Персональные_данныеItem _Персональные_данныеItem_GetImplementationValue(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Персональные_данныеItem, global::LightSwitchApplication.Персональные_данныеItem.DetailsClass>(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, ref d._Персональные_данныеItem);
                }
                private static void _Персональные_данныеItem_SetImplementationValue(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d, global::LightSwitchApplication.Персональные_данныеItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, ref d._Персональные_данныеItem, (i, ev) => i.Персональные_данныеItem = ev, v);
                }
                private static void _Персональные_данныеItem_Refresh(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, ref d._Персональные_данныеItem);
                }
                private static void _Персональные_данныеItem_OnValueChanged(global::LightSwitchApplication.Паспортные_данныеItem e)
                {
                    e.Персональные_данныеItem_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, int>.Data _Личный_Номер;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<int>>.Data _Данные_паспорта_серия;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<int>>.Data _Данные_паспорта_номер;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _Данные_паспорта_дата_выдачи;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, string>.Data _Данные_паспорта_кем_выдан;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Паспортные_данныеItem, global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Data _Персональные_данныеItem;
            
        }
    
        #endregion
    }
    
    #endregion
}
