

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Закрепленное_жильеItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Закрепленное_жильеItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Закрепленное_жильеItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Закрепленное_жильеItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Закрепленное_жильеItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Закрепленное_жильеItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Закрепленное_жильеItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Личный_номер
        {
            get
            {
                return global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.Личный_номер);
            }
            set
            {
                global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.Личный_номер, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Личный_номер_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Личный_номер_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Личный_номер_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> C_распоряжения_о_закреплении
        {
            get
            {
                return global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.C_распоряжения_о_закреплении);
            }
            set
            {
                global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.C_распоряжения_о_закреплении, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void C_распоряжения_о_закреплении_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void C_распоряжения_о_закреплении_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void C_распоряжения_о_закреплении_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> Дата_распоряжения_о_закреплении
        {
            get
            {
                return global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.Дата_распоряжения_о_закреплении);
            }
            set
            {
                global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.Дата_распоряжения_о_закреплении, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Дата_распоряжения_о_закреплении_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Дата_распоряжения_о_закреплении_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Дата_распоряжения_о_закреплении_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Персональные_данныеItem Персональные_данныеItem
        {
            get
            {
                return global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.Персональные_данныеItem);
            }
            set
            {
                global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItem_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Закрепленное_жильеItem,
                global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass,
                global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.Личный_номер;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass>.Entry
                __Закрепленное_жильеItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.__Закрепленное_жильеItem_CreateNew,
                    global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.__Закрепленное_жильеItem_Created,
                    global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.__Закрепленное_жильеItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Закрепленное_жильеItem __Закрепленное_жильеItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Закрепленное_жильеItem> es)
            {
                return new global::LightSwitchApplication.Закрепленное_жильеItem(es);
            }
            private static void __Закрепленное_жильеItem_Created(global::LightSwitchApplication.Закрепленное_жильеItem e)
            {
                e.Закрепленное_жильеItem_Created();
            }
            private static bool __Закрепленное_жильеItem_AllowSaveWithErrors(global::LightSwitchApplication.Закрепленное_жильеItem e)
            {
                bool result = false;
                e.Закрепленное_жильеItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, int> Личный_номер
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.Личный_номер) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::System.Nullable<int>> C_распоряжения_о_закреплении
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.C_распоряжения_о_закреплении) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::System.Nullable<global::System.DateTime>> Дата_распоряжения_о_закреплении
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.Дата_распоряжения_о_закреплении) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem> Персональные_данныеItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.Персональные_данныеItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Личный_номер { get; set; }
                new global::System.Nullable<int> C_распоряжения_о_закреплении { get; set; }
                new global::System.Nullable<global::System.DateTime> Дата_распоряжения_о_закреплении { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Персональные_данныеItem { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, int>.Entry
                    Личный_номер = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, int>.Entry(
                        "Личный_номер",
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Личный_номер_Stub,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Личный_номер_ComputeIsReadOnly,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Личный_номер_Validate,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Личный_номер_GetImplementationValue,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Личный_номер_SetImplementationValue,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Личный_номер_OnValueChanged);
                private static void _Личный_номер_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Личный_номер, sf);
                }
                private static bool _Личный_номер_ComputeIsReadOnly(global::LightSwitchApplication.Закрепленное_жильеItem e)
                {
                    bool result = false;
                    e.Личный_номер_IsReadOnly(ref result);
                    return result;
                }
                private static void _Личный_номер_Validate(global::LightSwitchApplication.Закрепленное_жильеItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Личный_номер_Validate(r);
                }
                private static int _Личный_номер_GetImplementationValue(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Личный_номер;
                }
                private static void _Личный_номер_SetImplementationValue(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Личный_номер = v;
                }
                private static void _Личный_номер_OnValueChanged(global::LightSwitchApplication.Закрепленное_жильеItem e)
                {
                    e.Личный_номер_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::System.Nullable<int>>.Entry
                    C_распоряжения_о_закреплении = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::System.Nullable<int>>.Entry(
                        "C_распоряжения_о_закреплении",
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._C_распоряжения_о_закреплении_Stub,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._C_распоряжения_о_закреплении_ComputeIsReadOnly,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._C_распоряжения_о_закреплении_Validate,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._C_распоряжения_о_закреплении_GetImplementationValue,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._C_распоряжения_о_закреплении_SetImplementationValue,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._C_распоряжения_о_закреплении_OnValueChanged);
                private static void _C_распоряжения_о_закреплении_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass d, object sf)
                {
                    c(d, ref d._C_распоряжения_о_закреплении, sf);
                }
                private static bool _C_распоряжения_о_закреплении_ComputeIsReadOnly(global::LightSwitchApplication.Закрепленное_жильеItem e)
                {
                    bool result = false;
                    e.C_распоряжения_о_закреплении_IsReadOnly(ref result);
                    return result;
                }
                private static void _C_распоряжения_о_закреплении_Validate(global::LightSwitchApplication.Закрепленное_жильеItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.C_распоряжения_о_закреплении_Validate(r);
                }
                private static global::System.Nullable<int> _C_распоряжения_о_закреплении_GetImplementationValue(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass d)
                {
                    return d.ImplementationEntity.C_распоряжения_о_закреплении;
                }
                private static void _C_распоряжения_о_закреплении_SetImplementationValue(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.C_распоряжения_о_закреплении = v;
                }
                private static void _C_распоряжения_о_закреплении_OnValueChanged(global::LightSwitchApplication.Закрепленное_жильеItem e)
                {
                    e.C_распоряжения_о_закреплении_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    Дата_распоряжения_о_закреплении = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "Дата_распоряжения_о_закреплении",
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Дата_распоряжения_о_закреплении_Stub,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Дата_распоряжения_о_закреплении_ComputeIsReadOnly,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Дата_распоряжения_о_закреплении_Validate,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Дата_распоряжения_о_закреплении_GetImplementationValue,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Дата_распоряжения_о_закреплении_SetImplementationValue,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Дата_распоряжения_о_закреплении_OnValueChanged);
                private static void _Дата_распоряжения_о_закреплении_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Дата_распоряжения_о_закреплении, sf);
                }
                private static bool _Дата_распоряжения_о_закреплении_ComputeIsReadOnly(global::LightSwitchApplication.Закрепленное_жильеItem e)
                {
                    bool result = false;
                    e.Дата_распоряжения_о_закреплении_IsReadOnly(ref result);
                    return result;
                }
                private static void _Дата_распоряжения_о_закреплении_Validate(global::LightSwitchApplication.Закрепленное_жильеItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Дата_распоряжения_о_закреплении_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _Дата_распоряжения_о_закреплении_GetImplementationValue(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Дата_распоряжения_о_закреплении;
                }
                private static void _Дата_распоряжения_о_закреплении_SetImplementationValue(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.Дата_распоряжения_о_закреплении = global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _Дата_распоряжения_о_закреплении_OnValueChanged(global::LightSwitchApplication.Закрепленное_жильеItem e)
                {
                    e.Дата_распоряжения_о_закреплении_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Entry
                    Персональные_данныеItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Entry(
                        "Персональные_данныеItem",
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_Stub,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_Validate,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_GetImplementationValue,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_SetImplementationValue,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_Refresh,
                        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_OnValueChanged);
                private static void _Персональные_данныеItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Data> c, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Персональные_данныеItem, sf);
                }
                private static bool _Персональные_данныеItem_ComputeIsReadOnly(global::LightSwitchApplication.Закрепленное_жильеItem e)
                {
                    bool result = false;
                    e.Персональные_данныеItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _Персональные_данныеItem_Validate(global::LightSwitchApplication.Закрепленное_жильеItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Персональные_данныеItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Персональные_данныеItem_GetCoreImplementationValue(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Персональные_данныеItem;
                }
                private static global::LightSwitchApplication.Персональные_данныеItem _Персональные_данныеItem_GetImplementationValue(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Персональные_данныеItem, global::LightSwitchApplication.Персональные_данныеItem.DetailsClass>(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, ref d._Персональные_данныеItem);
                }
                private static void _Персональные_данныеItem_SetImplementationValue(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass d, global::LightSwitchApplication.Персональные_данныеItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, ref d._Персональные_данныеItem, (i, ev) => i.Персональные_данныеItem = ev, v);
                }
                private static void _Персональные_данныеItem_Refresh(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, ref d._Персональные_данныеItem);
                }
                private static void _Персональные_данныеItem_OnValueChanged(global::LightSwitchApplication.Закрепленное_жильеItem e)
                {
                    e.Персональные_данныеItem_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, int>.Data _Личный_номер;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::System.Nullable<int>>.Data _C_распоряжения_о_закреплении;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _Дата_распоряжения_о_закреплении;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Закрепленное_жильеItem, global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Data _Персональные_данныеItem;
            
        }
    
        #endregion
    }
    
    #endregion
}
