

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Тип_семьиItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Тип_семьиItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Тип_семьиItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Тип_семьиItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Тип_семьиItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Тип_семьиItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Тип_семьиItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Тип_семьиItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Личный_номер
        {
            get
            {
                return global::LightSwitchApplication.Тип_семьиItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties.Личный_номер);
            }
            set
            {
                global::LightSwitchApplication.Тип_семьиItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties.Личный_номер, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Личный_номер_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Личный_номер_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Личный_номер_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Статус_семьи
        {
            get
            {
                return global::LightSwitchApplication.Тип_семьиItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties.Статус_семьи);
            }
            set
            {
                global::LightSwitchApplication.Тип_семьиItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties.Статус_семьи, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Статус_семьи_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Статус_семьи_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Статус_семьи_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Персональные_данныеItem Персональные_данныеItem
        {
            get
            {
                return global::LightSwitchApplication.Тип_семьиItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties.Персональные_данныеItem);
            }
            set
            {
                global::LightSwitchApplication.Тип_семьиItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItem_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Тип_семьиItem,
                global::LightSwitchApplication.Тип_семьиItem.DetailsClass,
                global::LightSwitchApplication.Тип_семьиItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties.Личный_номер;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass>.Entry
                __Тип_семьиItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.Тип_семьиItem.DetailsClass.__Тип_семьиItem_CreateNew,
                    global::LightSwitchApplication.Тип_семьиItem.DetailsClass.__Тип_семьиItem_Created,
                    global::LightSwitchApplication.Тип_семьиItem.DetailsClass.__Тип_семьиItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Тип_семьиItem __Тип_семьиItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Тип_семьиItem> es)
            {
                return new global::LightSwitchApplication.Тип_семьиItem(es);
            }
            private static void __Тип_семьиItem_Created(global::LightSwitchApplication.Тип_семьиItem e)
            {
                e.Тип_семьиItem_Created();
            }
            private static bool __Тип_семьиItem_AllowSaveWithErrors(global::LightSwitchApplication.Тип_семьиItem e)
            {
                bool result = false;
                e.Тип_семьиItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, int> Личный_номер
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties.Личный_номер) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, string> Статус_семьи
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties.Статус_семьи) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem> Персональные_данныеItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties.Персональные_данныеItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Личный_номер { get; set; }
                new string Статус_семьи { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Персональные_данныеItem { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, int>.Entry
                    Личный_номер = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, int>.Entry(
                        "Личный_номер",
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Личный_номер_Stub,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Личный_номер_ComputeIsReadOnly,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Личный_номер_Validate,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Личный_номер_GetImplementationValue,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Личный_номер_SetImplementationValue,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Личный_номер_OnValueChanged);
                private static void _Личный_номер_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Тип_семьиItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.Тип_семьиItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Личный_номер, sf);
                }
                private static bool _Личный_номер_ComputeIsReadOnly(global::LightSwitchApplication.Тип_семьиItem e)
                {
                    bool result = false;
                    e.Личный_номер_IsReadOnly(ref result);
                    return result;
                }
                private static void _Личный_номер_Validate(global::LightSwitchApplication.Тип_семьиItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Личный_номер_Validate(r);
                }
                private static int _Личный_номер_GetImplementationValue(global::LightSwitchApplication.Тип_семьиItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Личный_номер;
                }
                private static void _Личный_номер_SetImplementationValue(global::LightSwitchApplication.Тип_семьиItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Личный_номер = v;
                }
                private static void _Личный_номер_OnValueChanged(global::LightSwitchApplication.Тип_семьиItem e)
                {
                    e.Личный_номер_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, string>.Entry
                    Статус_семьи = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, string>.Entry(
                        "Статус_семьи",
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Статус_семьи_Stub,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Статус_семьи_ComputeIsReadOnly,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Статус_семьи_Validate,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Статус_семьи_GetImplementationValue,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Статус_семьи_SetImplementationValue,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Статус_семьи_OnValueChanged);
                private static void _Статус_семьи_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Тип_семьиItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.Тип_семьиItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Статус_семьи, sf);
                }
                private static bool _Статус_семьи_ComputeIsReadOnly(global::LightSwitchApplication.Тип_семьиItem e)
                {
                    bool result = false;
                    e.Статус_семьи_IsReadOnly(ref result);
                    return result;
                }
                private static void _Статус_семьи_Validate(global::LightSwitchApplication.Тип_семьиItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Статус_семьи_Validate(r);
                }
                private static string _Статус_семьи_GetImplementationValue(global::LightSwitchApplication.Тип_семьиItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Статус_семьи;
                }
                private static void _Статус_семьи_SetImplementationValue(global::LightSwitchApplication.Тип_семьиItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Статус_семьи = v;
                }
                private static void _Статус_семьи_OnValueChanged(global::LightSwitchApplication.Тип_семьиItem e)
                {
                    e.Статус_семьи_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Entry
                    Персональные_данныеItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Entry(
                        "Персональные_данныеItem",
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_Stub,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_Validate,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_GetImplementationValue,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_SetImplementationValue,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_Refresh,
                        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_OnValueChanged);
                private static void _Персональные_данныеItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Тип_семьиItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Data> c, global::LightSwitchApplication.Тип_семьиItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Персональные_данныеItem, sf);
                }
                private static bool _Персональные_данныеItem_ComputeIsReadOnly(global::LightSwitchApplication.Тип_семьиItem e)
                {
                    bool result = false;
                    e.Персональные_данныеItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _Персональные_данныеItem_Validate(global::LightSwitchApplication.Тип_семьиItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Персональные_данныеItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Персональные_данныеItem_GetCoreImplementationValue(global::LightSwitchApplication.Тип_семьиItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Персональные_данныеItem;
                }
                private static global::LightSwitchApplication.Персональные_данныеItem _Персональные_данныеItem_GetImplementationValue(global::LightSwitchApplication.Тип_семьиItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Персональные_данныеItem, global::LightSwitchApplication.Персональные_данныеItem.DetailsClass>(global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, ref d._Персональные_данныеItem);
                }
                private static void _Персональные_данныеItem_SetImplementationValue(global::LightSwitchApplication.Тип_семьиItem.DetailsClass d, global::LightSwitchApplication.Персональные_данныеItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, ref d._Персональные_данныеItem, (i, ev) => i.Персональные_данныеItem = ev, v);
                }
                private static void _Персональные_данныеItem_Refresh(global::LightSwitchApplication.Тип_семьиItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Тип_семьиItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, ref d._Персональные_данныеItem);
                }
                private static void _Персональные_данныеItem_OnValueChanged(global::LightSwitchApplication.Тип_семьиItem e)
                {
                    e.Персональные_данныеItem_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, int>.Data _Личный_номер;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, string>.Data _Статус_семьи;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Тип_семьиItem, global::LightSwitchApplication.Тип_семьиItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Data _Персональные_данныеItem;
            
        }
    
        #endregion
    }
    
    #endregion
}
