

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Свид_о_смертиItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Свид_о_смертиItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Свид_о_смертиItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Свид_о_смертиItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Свид_о_смертиItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Свид_о_смертиItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Свид_о_смертиItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Номерсв
        {
            get
            {
                return global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Номерсв);
            }
            set
            {
                global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Номерсв, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Номерсв_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Номерсв_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Номерсв_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> Дата_смерти
        {
            get
            {
                return global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Дата_смерти);
            }
            set
            {
                global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Дата_смерти, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Дата_смерти_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Дата_смерти_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Дата_смерти_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> Свид_о_смерти_дата_выдачи
        {
            get
            {
                return global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Свид_о_смерти_дата_выдачи);
            }
            set
            {
                global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Свид_о_смерти_дата_выдачи, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Свид_о_смерти_дата_выдачи_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Свид_о_смерти_дата_выдачи_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Свид_о_смерти_дата_выдачи_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Св_о_смерти_выдано
        {
            get
            {
                return global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Св_о_смерти_выдано);
            }
            set
            {
                global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Св_о_смерти_выдано, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Св_о_смерти_выдано_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Св_о_смерти_выдано_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Св_о_смерти_выдано_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Серия
        {
            get
            {
                return global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Серия);
            }
            set
            {
                global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Серия, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Серия_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Серия_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Серия_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Номер
        {
            get
            {
                return global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Номер);
            }
            set
            {
                global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Номер, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Номер_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Номер_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Номер_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.РодителиItem> Родители
        {
            get
            {
                return global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Родители);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.РодителиItem> РодителиQuery
        {
            get
            {
                return global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Родители);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Свид_о_смертиItem,
                global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass,
                global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Номерсв;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass>.Entry
                __Свид_о_смертиItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.__Свид_о_смертиItem_CreateNew,
                    global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.__Свид_о_смертиItem_Created,
                    global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.__Свид_о_смертиItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Свид_о_смертиItem __Свид_о_смертиItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Свид_о_смертиItem> es)
            {
                return new global::LightSwitchApplication.Свид_о_смертиItem(es);
            }
            private static void __Свид_о_смертиItem_Created(global::LightSwitchApplication.Свид_о_смертиItem e)
            {
                e.Свид_о_смертиItem_Created();
            }
            private static bool __Свид_о_смертиItem_AllowSaveWithErrors(global::LightSwitchApplication.Свид_о_смертиItem e)
            {
                bool result = false;
                e.Свид_о_смертиItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, int> Номерсв
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Номерсв) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<global::System.DateTime>> Дата_смерти
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Дата_смерти) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<global::System.DateTime>> Свид_о_смерти_дата_выдачи
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Свид_о_смерти_дата_выдачи) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, string> Св_о_смерти_выдано
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Св_о_смерти_выдано) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<int>> Серия
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Серия) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<int>> Номер
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Номер) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::LightSwitchApplication.РодителиItem> Родители
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Родители) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::LightSwitchApplication.РодителиItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Номерсв { get; set; }
                new global::System.Nullable<global::System.DateTime> Дата_смерти { get; set; }
                new global::System.Nullable<global::System.DateTime> Свид_о_смерти_дата_выдачи { get; set; }
                new string Св_о_смерти_выдано { get; set; }
                new global::System.Nullable<int> Серия { get; set; }
                new global::System.Nullable<int> Номер { get; set; }
                new global::System.Collections.IEnumerable Родители { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, int>.Entry
                    Номерсв = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, int>.Entry(
                        "Номерсв",
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Номерсв_Stub,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Номерсв_ComputeIsReadOnly,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Номерсв_Validate,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Номерсв_GetImplementationValue,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Номерсв_SetImplementationValue,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Номерсв_OnValueChanged);
                private static void _Номерсв_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Номерсв, sf);
                }
                private static bool _Номерсв_ComputeIsReadOnly(global::LightSwitchApplication.Свид_о_смертиItem e)
                {
                    bool result = false;
                    e.Номерсв_IsReadOnly(ref result);
                    return result;
                }
                private static void _Номерсв_Validate(global::LightSwitchApplication.Свид_о_смертиItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Номерсв_Validate(r);
                }
                private static int _Номерсв_GetImplementationValue(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Номерсв;
                }
                private static void _Номерсв_SetImplementationValue(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Номерсв = v;
                }
                private static void _Номерсв_OnValueChanged(global::LightSwitchApplication.Свид_о_смертиItem e)
                {
                    e.Номерсв_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    Дата_смерти = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "Дата_смерти",
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Дата_смерти_Stub,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Дата_смерти_ComputeIsReadOnly,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Дата_смерти_Validate,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Дата_смерти_GetImplementationValue,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Дата_смерти_SetImplementationValue,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Дата_смерти_OnValueChanged);
                private static void _Дата_смерти_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Дата_смерти, sf);
                }
                private static bool _Дата_смерти_ComputeIsReadOnly(global::LightSwitchApplication.Свид_о_смертиItem e)
                {
                    bool result = false;
                    e.Дата_смерти_IsReadOnly(ref result);
                    return result;
                }
                private static void _Дата_смерти_Validate(global::LightSwitchApplication.Свид_о_смертиItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Дата_смерти_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _Дата_смерти_GetImplementationValue(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Дата_смерти;
                }
                private static void _Дата_смерти_SetImplementationValue(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.Дата_смерти = global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _Дата_смерти_OnValueChanged(global::LightSwitchApplication.Свид_о_смертиItem e)
                {
                    e.Дата_смерти_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    Свид_о_смерти_дата_выдачи = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "Свид_о_смерти_дата_выдачи",
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Свид_о_смерти_дата_выдачи_Stub,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Свид_о_смерти_дата_выдачи_ComputeIsReadOnly,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Свид_о_смерти_дата_выдачи_Validate,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Свид_о_смерти_дата_выдачи_GetImplementationValue,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Свид_о_смерти_дата_выдачи_SetImplementationValue,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Свид_о_смерти_дата_выдачи_OnValueChanged);
                private static void _Свид_о_смерти_дата_выдачи_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Свид_о_смерти_дата_выдачи, sf);
                }
                private static bool _Свид_о_смерти_дата_выдачи_ComputeIsReadOnly(global::LightSwitchApplication.Свид_о_смертиItem e)
                {
                    bool result = false;
                    e.Свид_о_смерти_дата_выдачи_IsReadOnly(ref result);
                    return result;
                }
                private static void _Свид_о_смерти_дата_выдачи_Validate(global::LightSwitchApplication.Свид_о_смертиItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Свид_о_смерти_дата_выдачи_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _Свид_о_смерти_дата_выдачи_GetImplementationValue(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Свид_о_смерти_дата_выдачи;
                }
                private static void _Свид_о_смерти_дата_выдачи_SetImplementationValue(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.Свид_о_смерти_дата_выдачи = global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _Свид_о_смерти_дата_выдачи_OnValueChanged(global::LightSwitchApplication.Свид_о_смертиItem e)
                {
                    e.Свид_о_смерти_дата_выдачи_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, string>.Entry
                    Св_о_смерти_выдано = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, string>.Entry(
                        "Св_о_смерти_выдано",
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Св_о_смерти_выдано_Stub,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Св_о_смерти_выдано_ComputeIsReadOnly,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Св_о_смерти_выдано_Validate,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Св_о_смерти_выдано_GetImplementationValue,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Св_о_смерти_выдано_SetImplementationValue,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Св_о_смерти_выдано_OnValueChanged);
                private static void _Св_о_смерти_выдано_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Св_о_смерти_выдано, sf);
                }
                private static bool _Св_о_смерти_выдано_ComputeIsReadOnly(global::LightSwitchApplication.Свид_о_смертиItem e)
                {
                    bool result = false;
                    e.Св_о_смерти_выдано_IsReadOnly(ref result);
                    return result;
                }
                private static void _Св_о_смерти_выдано_Validate(global::LightSwitchApplication.Свид_о_смертиItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Св_о_смерти_выдано_Validate(r);
                }
                private static string _Св_о_смерти_выдано_GetImplementationValue(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Св_о_смерти_выдано;
                }
                private static void _Св_о_смерти_выдано_SetImplementationValue(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Св_о_смерти_выдано = v;
                }
                private static void _Св_о_смерти_выдано_OnValueChanged(global::LightSwitchApplication.Свид_о_смертиItem e)
                {
                    e.Св_о_смерти_выдано_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<int>>.Entry
                    Серия = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Серия",
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Серия_Stub,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Серия_ComputeIsReadOnly,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Серия_Validate,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Серия_GetImplementationValue,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Серия_SetImplementationValue,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Серия_OnValueChanged);
                private static void _Серия_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Серия, sf);
                }
                private static bool _Серия_ComputeIsReadOnly(global::LightSwitchApplication.Свид_о_смертиItem e)
                {
                    bool result = false;
                    e.Серия_IsReadOnly(ref result);
                    return result;
                }
                private static void _Серия_Validate(global::LightSwitchApplication.Свид_о_смертиItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Серия_Validate(r);
                }
                private static global::System.Nullable<int> _Серия_GetImplementationValue(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Серия;
                }
                private static void _Серия_SetImplementationValue(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Серия = v;
                }
                private static void _Серия_OnValueChanged(global::LightSwitchApplication.Свид_о_смертиItem e)
                {
                    e.Серия_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<int>>.Entry
                    Номер = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Номер",
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Номер_Stub,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Номер_ComputeIsReadOnly,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Номер_Validate,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Номер_GetImplementationValue,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Номер_SetImplementationValue,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Номер_OnValueChanged);
                private static void _Номер_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Номер, sf);
                }
                private static bool _Номер_ComputeIsReadOnly(global::LightSwitchApplication.Свид_о_смертиItem e)
                {
                    bool result = false;
                    e.Номер_IsReadOnly(ref result);
                    return result;
                }
                private static void _Номер_Validate(global::LightSwitchApplication.Свид_о_смертиItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Номер_Validate(r);
                }
                private static global::System.Nullable<int> _Номер_GetImplementationValue(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Номер;
                }
                private static void _Номер_SetImplementationValue(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Номер = v;
                }
                private static void _Номер_OnValueChanged(global::LightSwitchApplication.Свид_о_смертиItem e)
                {
                    e.Номер_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::LightSwitchApplication.РодителиItem>.Entry
                    Родители = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::LightSwitchApplication.РодителиItem>.Entry(
                        "Родители",
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Родители_Stub,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Родители_GetReferencedEntities,
                        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties._Родители_GetEntityCollection);
                private static void _Родители_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::LightSwitchApplication.РодителиItem>.Data> c, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Родители, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.РодителиItem> _Родители_GetReferencedEntities(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.РодителиItem, global::LightSwitchApplication.РодителиItem.DetailsClass>(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.PropertySetProperties.Родители, ref d._Родители);
                }
                private static global::System.Collections.IEnumerable _Родители_GetEntityCollection(global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Родители;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, int>.Data _Номерсв;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _Дата_смерти;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _Свид_о_смерти_дата_выдачи;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, string>.Data _Св_о_смерти_выдано;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<int>>.Data _Серия;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::System.Nullable<int>>.Data _Номер;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Свид_о_смертиItem, global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass, global::LightSwitchApplication.РодителиItem>.Data _Родители;
            
        }
    
        #endregion
    }
    
    #endregion
}
