

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Документы_ребенкаItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Документы_ребенкаItem entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Документы_ребенкаItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Документы_ребенкаItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Документы_ребенкаItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Документы_ребенкаItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Документы_ребенкаItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Личный_номер
        {
            get
            {
                return global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Личный_номер);
            }
            set
            {
                global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Личный_номер, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Личный_номер_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Личный_номер_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Личный_номер_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Данные_свидетельства_о_рождении_номер
        {
            get
            {
                return global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении_номер);
            }
            set
            {
                global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении_номер, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении_номер_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении_номер_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении_номер_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Данные_свидетельства_о_рождении_серия
        {
            get
            {
                return global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении_серия);
            }
            set
            {
                global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении_серия, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении_серия_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении_серия_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении_серия_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Данные_свидетельства_о_рождении__серия
        {
            get
            {
                return global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении__серия);
            }
            set
            {
                global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении__серия, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении__серия_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении__серия_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении__серия_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> Данные_свидетельства_о_рождении_дата_выдачи
        {
            get
            {
                return global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении_дата_выдачи);
            }
            set
            {
                global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении_дата_выдачи, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении_дата_выдачи_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении_дата_выдачи_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении_дата_выдачи_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Данные_свидетельства_о_рождении_кем_выдано
        {
            get
            {
                return global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении_кем_выдано);
            }
            set
            {
                global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении_кем_выдано, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении_кем_выдано_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении_кем_выдано_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Данные_свидетельства_о_рождении_кем_выдано_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> ИНН_номер
        {
            get
            {
                return global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.ИНН_номер);
            }
            set
            {
                global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.ИНН_номер, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ИНН_номер_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ИНН_номер_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ИНН_номер_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> ИНН_дата
        {
            get
            {
                return global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.ИНН_дата);
            }
            set
            {
                global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.ИНН_дата, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ИНН_дата_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ИНН_дата_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ИНН_дата_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Персональные_данныеItem Персональные_данныеItem
        {
            get
            {
                return global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Персональные_данныеItem);
            }
            set
            {
                global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItem_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Документы_ребенкаItem,
                global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass,
                global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Личный_номер;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass>.Entry
                __Документы_ребенкаItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.__Документы_ребенкаItem_CreateNew,
                    global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.__Документы_ребенкаItem_Created,
                    global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.__Документы_ребенкаItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Документы_ребенкаItem __Документы_ребенкаItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Документы_ребенкаItem> es)
            {
                return new global::LightSwitchApplication.Документы_ребенкаItem(es);
            }
            private static void __Документы_ребенкаItem_Created(global::LightSwitchApplication.Документы_ребенкаItem e)
            {
                e.Документы_ребенкаItem_Created();
            }
            private static bool __Документы_ребенкаItem_AllowSaveWithErrors(global::LightSwitchApplication.Документы_ребенкаItem e)
            {
                bool result = false;
                e.Документы_ребенкаItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, int> Личный_номер
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Личный_номер) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<int>> Данные_свидетельства_о_рождении_номер
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении_номер) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string> Данные_свидетельства_о_рождении_серия
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении_серия) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string> Данные_свидетельства_о_рождении__серия
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении__серия) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<global::System.DateTime>> Данные_свидетельства_о_рождении_дата_выдачи
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении_дата_выдачи) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string> Данные_свидетельства_о_рождении_кем_выдано
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Данные_свидетельства_о_рождении_кем_выдано) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<int>> ИНН_номер
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.ИНН_номер) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<global::System.DateTime>> ИНН_дата
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.ИНН_дата) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem> Персональные_данныеItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Персональные_данныеItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Личный_номер { get; set; }
                new global::System.Nullable<int> Данные_свидетельства_о_рождении_номер { get; set; }
                new string Данные_свидетельства_о_рождении_серия { get; set; }
                new string Данные_свидетельства_о_рождении__серия { get; set; }
                new global::System.Nullable<global::System.DateTime> Данные_свидетельства_о_рождении_дата_выдачи { get; set; }
                new string Данные_свидетельства_о_рождении_кем_выдано { get; set; }
                new global::System.Nullable<int> ИНН_номер { get; set; }
                new global::System.Nullable<global::System.DateTime> ИНН_дата { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Персональные_данныеItem { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, int>.Entry
                    Личный_номер = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, int>.Entry(
                        "Личный_номер",
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Личный_номер_Stub,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Личный_номер_ComputeIsReadOnly,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Личный_номер_Validate,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Личный_номер_GetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Личный_номер_SetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Личный_номер_OnValueChanged);
                private static void _Личный_номер_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Личный_номер, sf);
                }
                private static bool _Личный_номер_ComputeIsReadOnly(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    bool result = false;
                    e.Личный_номер_IsReadOnly(ref result);
                    return result;
                }
                private static void _Личный_номер_Validate(global::LightSwitchApplication.Документы_ребенкаItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Личный_номер_Validate(r);
                }
                private static int _Личный_номер_GetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Личный_номер;
                }
                private static void _Личный_номер_SetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Личный_номер = v;
                }
                private static void _Личный_номер_OnValueChanged(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    e.Личный_номер_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<int>>.Entry
                    Данные_свидетельства_о_рождении_номер = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Данные_свидетельства_о_рождении_номер",
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_номер_Stub,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_номер_ComputeIsReadOnly,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_номер_Validate,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_номер_GetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_номер_SetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_номер_OnValueChanged);
                private static void _Данные_свидетельства_о_рождении_номер_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Данные_свидетельства_о_рождении_номер, sf);
                }
                private static bool _Данные_свидетельства_о_рождении_номер_ComputeIsReadOnly(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    bool result = false;
                    e.Данные_свидетельства_о_рождении_номер_IsReadOnly(ref result);
                    return result;
                }
                private static void _Данные_свидетельства_о_рождении_номер_Validate(global::LightSwitchApplication.Документы_ребенкаItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Данные_свидетельства_о_рождении_номер_Validate(r);
                }
                private static global::System.Nullable<int> _Данные_свидетельства_о_рождении_номер_GetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Данные_свидетельства_о_рождении_номер;
                }
                private static void _Данные_свидетельства_о_рождении_номер_SetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Данные_свидетельства_о_рождении_номер = v;
                }
                private static void _Данные_свидетельства_о_рождении_номер_OnValueChanged(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    e.Данные_свидетельства_о_рождении_номер_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>.Entry
                    Данные_свидетельства_о_рождении_серия = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>.Entry(
                        "Данные_свидетельства_о_рождении_серия",
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_серия_Stub,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_серия_ComputeIsReadOnly,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_серия_Validate,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_серия_GetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_серия_SetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_серия_OnValueChanged);
                private static void _Данные_свидетельства_о_рождении_серия_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Данные_свидетельства_о_рождении_серия, sf);
                }
                private static bool _Данные_свидетельства_о_рождении_серия_ComputeIsReadOnly(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    bool result = false;
                    e.Данные_свидетельства_о_рождении_серия_IsReadOnly(ref result);
                    return result;
                }
                private static void _Данные_свидетельства_о_рождении_серия_Validate(global::LightSwitchApplication.Документы_ребенкаItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Данные_свидетельства_о_рождении_серия_Validate(r);
                }
                private static string _Данные_свидетельства_о_рождении_серия_GetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Данные_свидетельства_о_рождении_серия;
                }
                private static void _Данные_свидетельства_о_рождении_серия_SetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Данные_свидетельства_о_рождении_серия = v;
                }
                private static void _Данные_свидетельства_о_рождении_серия_OnValueChanged(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    e.Данные_свидетельства_о_рождении_серия_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>.Entry
                    Данные_свидетельства_о_рождении__серия = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>.Entry(
                        "Данные_свидетельства_о_рождении__серия",
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении__серия_Stub,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении__серия_ComputeIsReadOnly,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении__серия_Validate,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении__серия_GetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении__серия_SetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении__серия_OnValueChanged);
                private static void _Данные_свидетельства_о_рождении__серия_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Данные_свидетельства_о_рождении__серия, sf);
                }
                private static bool _Данные_свидетельства_о_рождении__серия_ComputeIsReadOnly(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    bool result = false;
                    e.Данные_свидетельства_о_рождении__серия_IsReadOnly(ref result);
                    return result;
                }
                private static void _Данные_свидетельства_о_рождении__серия_Validate(global::LightSwitchApplication.Документы_ребенкаItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Данные_свидетельства_о_рождении__серия_Validate(r);
                }
                private static string _Данные_свидетельства_о_рождении__серия_GetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Данные_свидетельства_о_рождении__серия;
                }
                private static void _Данные_свидетельства_о_рождении__серия_SetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Данные_свидетельства_о_рождении__серия = v;
                }
                private static void _Данные_свидетельства_о_рождении__серия_OnValueChanged(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    e.Данные_свидетельства_о_рождении__серия_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    Данные_свидетельства_о_рождении_дата_выдачи = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "Данные_свидетельства_о_рождении_дата_выдачи",
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_дата_выдачи_Stub,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_дата_выдачи_ComputeIsReadOnly,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_дата_выдачи_Validate,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_дата_выдачи_GetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_дата_выдачи_SetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_дата_выдачи_OnValueChanged);
                private static void _Данные_свидетельства_о_рождении_дата_выдачи_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Данные_свидетельства_о_рождении_дата_выдачи, sf);
                }
                private static bool _Данные_свидетельства_о_рождении_дата_выдачи_ComputeIsReadOnly(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    bool result = false;
                    e.Данные_свидетельства_о_рождении_дата_выдачи_IsReadOnly(ref result);
                    return result;
                }
                private static void _Данные_свидетельства_о_рождении_дата_выдачи_Validate(global::LightSwitchApplication.Документы_ребенкаItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Данные_свидетельства_о_рождении_дата_выдачи_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _Данные_свидетельства_о_рождении_дата_выдачи_GetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Данные_свидетельства_о_рождении_дата_выдачи;
                }
                private static void _Данные_свидетельства_о_рождении_дата_выдачи_SetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.Данные_свидетельства_о_рождении_дата_выдачи = global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _Данные_свидетельства_о_рождении_дата_выдачи_OnValueChanged(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    e.Данные_свидетельства_о_рождении_дата_выдачи_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>.Entry
                    Данные_свидетельства_о_рождении_кем_выдано = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>.Entry(
                        "Данные_свидетельства_о_рождении_кем_выдано",
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_кем_выдано_Stub,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_кем_выдано_ComputeIsReadOnly,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_кем_выдано_Validate,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_кем_выдано_GetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_кем_выдано_SetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Данные_свидетельства_о_рождении_кем_выдано_OnValueChanged);
                private static void _Данные_свидетельства_о_рождении_кем_выдано_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Данные_свидетельства_о_рождении_кем_выдано, sf);
                }
                private static bool _Данные_свидетельства_о_рождении_кем_выдано_ComputeIsReadOnly(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    bool result = false;
                    e.Данные_свидетельства_о_рождении_кем_выдано_IsReadOnly(ref result);
                    return result;
                }
                private static void _Данные_свидетельства_о_рождении_кем_выдано_Validate(global::LightSwitchApplication.Документы_ребенкаItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Данные_свидетельства_о_рождении_кем_выдано_Validate(r);
                }
                private static string _Данные_свидетельства_о_рождении_кем_выдано_GetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Данные_свидетельства_о_рождении_кем_выдано;
                }
                private static void _Данные_свидетельства_о_рождении_кем_выдано_SetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Данные_свидетельства_о_рождении_кем_выдано = v;
                }
                private static void _Данные_свидетельства_о_рождении_кем_выдано_OnValueChanged(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    e.Данные_свидетельства_о_рождении_кем_выдано_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<int>>.Entry
                    ИНН_номер = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<int>>.Entry(
                        "ИНН_номер",
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._ИНН_номер_Stub,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._ИНН_номер_ComputeIsReadOnly,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._ИНН_номер_Validate,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._ИНН_номер_GetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._ИНН_номер_SetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._ИНН_номер_OnValueChanged);
                private static void _ИНН_номер_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ИНН_номер, sf);
                }
                private static bool _ИНН_номер_ComputeIsReadOnly(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    bool result = false;
                    e.ИНН_номер_IsReadOnly(ref result);
                    return result;
                }
                private static void _ИНН_номер_Validate(global::LightSwitchApplication.Документы_ребенкаItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ИНН_номер_Validate(r);
                }
                private static global::System.Nullable<int> _ИНН_номер_GetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ИНН_номер;
                }
                private static void _ИНН_номер_SetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.ИНН_номер = v;
                }
                private static void _ИНН_номер_OnValueChanged(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    e.ИНН_номер_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    ИНН_дата = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "ИНН_дата",
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._ИНН_дата_Stub,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._ИНН_дата_ComputeIsReadOnly,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._ИНН_дата_Validate,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._ИНН_дата_GetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._ИНН_дата_SetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._ИНН_дата_OnValueChanged);
                private static void _ИНН_дата_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ИНН_дата, sf);
                }
                private static bool _ИНН_дата_ComputeIsReadOnly(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    bool result = false;
                    e.ИНН_дата_IsReadOnly(ref result);
                    return result;
                }
                private static void _ИНН_дата_Validate(global::LightSwitchApplication.Документы_ребенкаItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ИНН_дата_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _ИНН_дата_GetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ИНН_дата;
                }
                private static void _ИНН_дата_SetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.ИНН_дата = global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ИНН_дата_OnValueChanged(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    e.ИНН_дата_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Entry
                    Персональные_данныеItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Entry(
                        "Персональные_данныеItem",
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_Stub,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_Validate,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_GetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_SetImplementationValue,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_Refresh,
                        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties._Персональные_данныеItem_OnValueChanged);
                private static void _Персональные_данныеItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Data> c, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Персональные_данныеItem, sf);
                }
                private static bool _Персональные_данныеItem_ComputeIsReadOnly(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    bool result = false;
                    e.Персональные_данныеItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _Персональные_данныеItem_Validate(global::LightSwitchApplication.Документы_ребенкаItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Персональные_данныеItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Персональные_данныеItem_GetCoreImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Персональные_данныеItem;
                }
                private static global::LightSwitchApplication.Персональные_данныеItem _Персональные_данныеItem_GetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Персональные_данныеItem, global::LightSwitchApplication.Персональные_данныеItem.DetailsClass>(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, ref d._Персональные_данныеItem);
                }
                private static void _Персональные_данныеItem_SetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d, global::LightSwitchApplication.Персональные_данныеItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, ref d._Персональные_данныеItem, (i, ev) => i.Персональные_данныеItem = ev, v);
                }
                private static void _Персональные_данныеItem_Refresh(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.PropertySetProperties.Персональные_данныеItem, ref d._Персональные_данныеItem);
                }
                private static void _Персональные_данныеItem_OnValueChanged(global::LightSwitchApplication.Документы_ребенкаItem e)
                {
                    e.Персональные_данныеItem_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, int>.Data _Личный_номер;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<int>>.Data _Данные_свидетельства_о_рождении_номер;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>.Data _Данные_свидетельства_о_рождении_серия;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>.Data _Данные_свидетельства_о_рождении__серия;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _Данные_свидетельства_о_рождении_дата_выдачи;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, string>.Data _Данные_свидетельства_о_рождении_кем_выдано;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<int>>.Data _ИНН_номер;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _ИНН_дата;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Документы_ребенкаItem, global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Data _Персональные_данныеItem;
            
        }
    
        #endregion
    }
    
    #endregion
}
