//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region АдресItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/NadejdaAzureData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class АдресItem :
        global::LightSwitchApplication.АдресItem.DetailsClass.IImplementation
    {
        partial void OnНомер_АдресChanged()
        {
            this.___OnPropertyChanged("Номер_Адрес");
        }
        
        partial void OnАдресChanged()
        {
            this.___OnPropertyChanged("Адрес");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.АдресItem.DetailsClass.IImplementation.Родители
        {
            get
            {
                return this.Родители;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.РодителиItem> __Родители
        {
            get
            {
                if (this.___Родители == null)
                {
                    this.___Родители = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.РодителиItem>(
                        this,
                        "Родители",
                        () => this._Родители,
                        e => global::System.Object.Equals(e.CАдрес, this.Номер_Адрес));
                }
                return this.___Родители;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.РодителиItem> ___Родители;
        
    }
    #endregion
    
    #region Документы_ребенкаItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/NadejdaAzureData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Документы_ребенкаItem :
        global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.IImplementation
    {
        partial void OnЛичный_номерChanged()
        {
            this.___OnPropertyChanged("Личный_номер");
            this.___OnPropertyChanged("Персональные_данныеItem");
        }
        
        partial void OnДанные_свидетельства_о_рождении_номерChanged()
        {
            this.___OnPropertyChanged("Данные_свидетельства_о_рождении_номер");
        }
        
        partial void OnДанные_свидетельства_о_рождении_серияChanged()
        {
            this.___OnPropertyChanged("Данные_свидетельства_о_рождении_серия");
        }
        
        partial void OnДанные_свидетельства_о_рождении__серияChanged()
        {
            this.___OnPropertyChanged("Данные_свидетельства_о_рождении__серия");
        }
        
        partial void OnДанные_свидетельства_о_рождении_дата_выдачиChanged()
        {
            this.___OnPropertyChanged("Данные_свидетельства_о_рождении_дата_выдачи");
        }
        
        partial void OnДанные_свидетельства_о_рождении_кем_выданоChanged()
        {
            this.___OnPropertyChanged("Данные_свидетельства_о_рождении_кем_выдано");
        }
        
        partial void OnИНН_номерChanged()
        {
            this.___OnPropertyChanged("ИНН_номер");
        }
        
        partial void OnИНН_датаChanged()
        {
            this.___OnPropertyChanged("ИНН_дата");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Документы_ребенкаItem.DetailsClass.IImplementation.Персональные_данныеItem
        {
            get
            {
                return this.Персональные_данныеItem;
            }
            set
            {
                this.Персональные_данныеItem = (global::LightSwitchApplication.Implementation.Персональные_данныеItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> __Персональные_данныеItem
        {
            get
            {
                if (this.___Персональные_данныеItem == null)
                {
                    this.___Персональные_данныеItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem>(
                        this,
                        "Персональные_данныеItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Персональные_данныеItem,
                        e => this._Персональные_данныеItem = e);
                }
                return this.___Персональные_данныеItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> ___Персональные_данныеItem;
        
    }
    #endregion
    
    #region Жилье_ребенкаItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/NadejdaAzureData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Жилье_ребенкаItem :
        global::LightSwitchApplication.Жилье_ребенкаItem.DetailsClass.IImplementation
    {
        partial void OnЛичный_номерChanged()
        {
            this.___OnPropertyChanged("Личный_номер");
            this.___OnPropertyChanged("Персональные_данныеItem");
        }
        
        partial void OnДоговорChanged()
        {
            this.___OnPropertyChanged("Договор");
        }
        
        partial void OnДата_договораChanged()
        {
            this.___OnPropertyChanged("Дата_договора");
        }
        
        partial void OnСерия_договораChanged()
        {
            this.___OnPropertyChanged("Серия_договора");
        }
        
        partial void OnНомер_договораChanged()
        {
            this.___OnPropertyChanged("Номер_договора");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Жилье_ребенкаItem.DetailsClass.IImplementation.Персональные_данныеItem
        {
            get
            {
                return this.Персональные_данныеItem;
            }
            set
            {
                this.Персональные_данныеItem = (global::LightSwitchApplication.Implementation.Персональные_данныеItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> __Персональные_данныеItem
        {
            get
            {
                if (this.___Персональные_данныеItem == null)
                {
                    this.___Персональные_данныеItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem>(
                        this,
                        "Персональные_данныеItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Персональные_данныеItem,
                        e => this._Персональные_данныеItem = e);
                }
                return this.___Персональные_данныеItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> ___Персональные_данныеItem;
        
    }
    #endregion
    
    #region Закрепленное_жильеItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/NadejdaAzureData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Закрепленное_жильеItem :
        global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.IImplementation
    {
        partial void OnЛичный_номерChanged()
        {
            this.___OnPropertyChanged("Личный_номер");
            this.___OnPropertyChanged("Персональные_данныеItem");
        }
        
        partial void OnC_распоряжения_о_закрепленииChanged()
        {
            this.___OnPropertyChanged("C_распоряжения_о_закреплении");
        }
        
        partial void OnДата_распоряжения_о_закрепленииChanged()
        {
            this.___OnPropertyChanged("Дата_распоряжения_о_закреплении");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Закрепленное_жильеItem.DetailsClass.IImplementation.Персональные_данныеItem
        {
            get
            {
                return this.Персональные_данныеItem;
            }
            set
            {
                this.Персональные_данныеItem = (global::LightSwitchApplication.Implementation.Персональные_данныеItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> __Персональные_данныеItem
        {
            get
            {
                if (this.___Персональные_данныеItem == null)
                {
                    this.___Персональные_данныеItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem>(
                        this,
                        "Персональные_данныеItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Персональные_данныеItem,
                        e => this._Персональные_данныеItem = e);
                }
                return this.___Персональные_данныеItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> ___Персональные_данныеItem;
        
    }
    #endregion
    
    #region Паспортные_данныеItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/NadejdaAzureData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Паспортные_данныеItem :
        global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.IImplementation
    {
        partial void OnЛичный_НомерChanged()
        {
            this.___OnPropertyChanged("Личный_Номер");
            this.___OnPropertyChanged("Персональные_данныеItem");
        }
        
        partial void OnДанные_паспорта_серияChanged()
        {
            this.___OnPropertyChanged("Данные_паспорта_серия");
        }
        
        partial void OnДанные_паспорта_номерChanged()
        {
            this.___OnPropertyChanged("Данные_паспорта_номер");
        }
        
        partial void OnДанные_паспорта_дата_выдачиChanged()
        {
            this.___OnPropertyChanged("Данные_паспорта_дата_выдачи");
        }
        
        partial void OnДанные_паспорта_кем_выданChanged()
        {
            this.___OnPropertyChanged("Данные_паспорта_кем_выдан");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Паспортные_данныеItem.DetailsClass.IImplementation.Персональные_данныеItem
        {
            get
            {
                return this.Персональные_данныеItem;
            }
            set
            {
                this.Персональные_данныеItem = (global::LightSwitchApplication.Implementation.Персональные_данныеItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> __Персональные_данныеItem
        {
            get
            {
                if (this.___Персональные_данныеItem == null)
                {
                    this.___Персональные_данныеItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem>(
                        this,
                        "Персональные_данныеItem",
                        new string[] { "Личный_Номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_Номер),
                        () => this._Персональные_данныеItem,
                        e => this._Персональные_данныеItem = e);
                }
                return this.___Персональные_данныеItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> ___Персональные_данныеItem;
        
    }
    #endregion
    
    #region ПенсияItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/NadejdaAzureData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ПенсияItem :
        global::LightSwitchApplication.ПенсияItem.DetailsClass.IImplementation
    {
        partial void OnЛичный_номерChanged()
        {
            this.___OnPropertyChanged("Личный_номер");
            this.___OnPropertyChanged("Персональные_данныеItem");
        }
        
        partial void OnC_пенсионного_делаChanged()
        {
            this.___OnPropertyChanged("C_пенсионного_дела");
        }
        
        partial void OnДата_оформленияChanged()
        {
            this.___OnPropertyChanged("Дата_оформления");
        }
        
        partial void OnПенсионное_страховое_свидетельство_номерChanged()
        {
            this.___OnPropertyChanged("Пенсионное_страховое_свидетельство_номер");
        }
        
        partial void OnПенсионное_страховое_свидетельство_датаChanged()
        {
            this.___OnPropertyChanged("Пенсионное_страховое_свидетельство_дата");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ПенсияItem.DetailsClass.IImplementation.Персональные_данныеItem
        {
            get
            {
                return this.Персональные_данныеItem;
            }
            set
            {
                this.Персональные_данныеItem = (global::LightSwitchApplication.Implementation.Персональные_данныеItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> __Персональные_данныеItem
        {
            get
            {
                if (this.___Персональные_данныеItem == null)
                {
                    this.___Персональные_данныеItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem>(
                        this,
                        "Персональные_данныеItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Персональные_данныеItem,
                        e => this._Персональные_данныеItem = e);
                }
                return this.___Персональные_данныеItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> ___Персональные_данныеItem;
        
    }
    #endregion
    
    #region Персональные_данныеItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/NadejdaAzureData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Персональные_данныеItem :
        global::LightSwitchApplication.Персональные_данныеItem.DetailsClass.IImplementation
    {
        partial void OnЛичный_номерChanged()
        {
            this.___OnPropertyChanged("Личный_номер");
        }
        
        partial void OnФотоChanged()
        {
            this.___OnPropertyChanged("Фото");
        }
        
        partial void OnФамилияChanged()
        {
            this.___OnPropertyChanged("Фамилия");
        }
        
        partial void OnИмяChanged()
        {
            this.___OnPropertyChanged("Имя");
        }
        
        partial void OnОтчествоChanged()
        {
            this.___OnPropertyChanged("Отчество");
        }
        
        partial void OnДата_рожденияChanged()
        {
            this.___OnPropertyChanged("Дата_рождения");
        }
        
        partial void OnДата_выбытияChanged()
        {
            this.___OnPropertyChanged("Дата_выбытия");
        }
        
        partial void OnПолных_летChanged()
        {
            this.___OnPropertyChanged("Полных_лет");
        }
        
        partial void OnАдресChanged()
        {
            this.___OnPropertyChanged("Адрес");
        }
        
        partial void OnГражданствоChanged()
        {
            this.___OnPropertyChanged("Гражданство");
        }
        
        partial void OnДата_поступленияChanged()
        {
            this.___OnPropertyChanged("Дата_поступления");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Персональные_данныеItem.DetailsClass.IImplementation.Документы_ребенкаItem
        {
            get
            {
                return this.Документы_ребенкаItem;
            }
            set
            {
                this.Документы_ребенкаItem = (global::LightSwitchApplication.Implementation.Документы_ребенкаItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Документы_ребенкаItem> __Документы_ребенкаItem
        {
            get
            {
                if (this.___Документы_ребенкаItem == null)
                {
                    this.___Документы_ребенкаItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Документы_ребенкаItem>(
                        this,
                        "Документы_ребенкаItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Документы_ребенкаItem,
                        e => this._Документы_ребенкаItem = e);
                }
                return this.___Документы_ребенкаItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Документы_ребенкаItem> ___Документы_ребенкаItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Персональные_данныеItem.DetailsClass.IImplementation.Жилье_ребенкаItem
        {
            get
            {
                return this.Жилье_ребенкаItem;
            }
            set
            {
                this.Жилье_ребенкаItem = (global::LightSwitchApplication.Implementation.Жилье_ребенкаItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Жилье_ребенкаItem> __Жилье_ребенкаItem
        {
            get
            {
                if (this.___Жилье_ребенкаItem == null)
                {
                    this.___Жилье_ребенкаItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Жилье_ребенкаItem>(
                        this,
                        "Жилье_ребенкаItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Жилье_ребенкаItem,
                        e => this._Жилье_ребенкаItem = e);
                }
                return this.___Жилье_ребенкаItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Жилье_ребенкаItem> ___Жилье_ребенкаItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Персональные_данныеItem.DetailsClass.IImplementation.Закрепленное_жильеItem
        {
            get
            {
                return this.Закрепленное_жильеItem;
            }
            set
            {
                this.Закрепленное_жильеItem = (global::LightSwitchApplication.Implementation.Закрепленное_жильеItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Закрепленное_жильеItem> __Закрепленное_жильеItem
        {
            get
            {
                if (this.___Закрепленное_жильеItem == null)
                {
                    this.___Закрепленное_жильеItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Закрепленное_жильеItem>(
                        this,
                        "Закрепленное_жильеItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Закрепленное_жильеItem,
                        e => this._Закрепленное_жильеItem = e);
                }
                return this.___Закрепленное_жильеItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Закрепленное_жильеItem> ___Закрепленное_жильеItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Персональные_данныеItem.DetailsClass.IImplementation.Паспортные_данныеItem
        {
            get
            {
                return this.Паспортные_данныеItem;
            }
            set
            {
                this.Паспортные_данныеItem = (global::LightSwitchApplication.Implementation.Паспортные_данныеItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Паспортные_данныеItem> __Паспортные_данныеItem
        {
            get
            {
                if (this.___Паспортные_данныеItem == null)
                {
                    this.___Паспортные_данныеItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Паспортные_данныеItem>(
                        this,
                        "Паспортные_данныеItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_Номер, this.Личный_номер),
                        () => this._Паспортные_данныеItem,
                        e => this._Паспортные_данныеItem = e);
                }
                return this.___Паспортные_данныеItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Паспортные_данныеItem> ___Паспортные_данныеItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Персональные_данныеItem.DetailsClass.IImplementation.ПенсияItem
        {
            get
            {
                return this.ПенсияItem;
            }
            set
            {
                this.ПенсияItem = (global::LightSwitchApplication.Implementation.ПенсияItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ПенсияItem> __ПенсияItem
        {
            get
            {
                if (this.___ПенсияItem == null)
                {
                    this.___ПенсияItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ПенсияItem>(
                        this,
                        "ПенсияItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._ПенсияItem,
                        e => this._ПенсияItem = e);
                }
                return this.___ПенсияItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ПенсияItem> ___ПенсияItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Персональные_данныеItem.DetailsClass.IImplementation.Поступление_в_приютItem
        {
            get
            {
                return this.Поступление_в_приютItem;
            }
            set
            {
                this.Поступление_в_приютItem = (global::LightSwitchApplication.Implementation.Поступление_в_приютItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Поступление_в_приютItem> __Поступление_в_приютItem
        {
            get
            {
                if (this.___Поступление_в_приютItem == null)
                {
                    this.___Поступление_в_приютItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Поступление_в_приютItem>(
                        this,
                        "Поступление_в_приютItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Поступление_в_приютItem,
                        e => this._Поступление_в_приютItem = e);
                }
                return this.___Поступление_в_приютItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Поступление_в_приютItem> ___Поступление_в_приютItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Персональные_данныеItem.DetailsClass.IImplementation.Регистрация_ребенкаItem
        {
            get
            {
                return this.Регистрация_ребенкаItem;
            }
            set
            {
                this.Регистрация_ребенкаItem = (global::LightSwitchApplication.Implementation.Регистрация_ребенкаItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Регистрация_ребенкаItem> __Регистрация_ребенкаItem
        {
            get
            {
                if (this.___Регистрация_ребенкаItem == null)
                {
                    this.___Регистрация_ребенкаItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Регистрация_ребенкаItem>(
                        this,
                        "Регистрация_ребенкаItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Регистрация_ребенкаItem,
                        e => this._Регистрация_ребенкаItem = e);
                }
                return this.___Регистрация_ребенкаItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Регистрация_ребенкаItem> ___Регистрация_ребенкаItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Персональные_данныеItem.DetailsClass.IImplementation.Тип_семьиItem
        {
            get
            {
                return this.Тип_семьиItem;
            }
            set
            {
                this.Тип_семьиItem = (global::LightSwitchApplication.Implementation.Тип_семьиItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Тип_семьиItem> __Тип_семьиItem
        {
            get
            {
                if (this.___Тип_семьиItem == null)
                {
                    this.___Тип_семьиItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Тип_семьиItem>(
                        this,
                        "Тип_семьиItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Тип_семьиItem,
                        e => this._Тип_семьиItem = e);
                }
                return this.___Тип_семьиItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Тип_семьиItem> ___Тип_семьиItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Персональные_данныеItem.DetailsClass.IImplementation.Улучшение_жильяItem
        {
            get
            {
                return this.Улучшение_жильяItem;
            }
            set
            {
                this.Улучшение_жильяItem = (global::LightSwitchApplication.Implementation.Улучшение_жильяItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Улучшение_жильяItem> __Улучшение_жильяItem
        {
            get
            {
                if (this.___Улучшение_жильяItem == null)
                {
                    this.___Улучшение_жильяItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Улучшение_жильяItem>(
                        this,
                        "Улучшение_жильяItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Улучшение_жильяItem,
                        e => this._Улучшение_жильяItem = e);
                }
                return this.___Улучшение_жильяItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Улучшение_жильяItem> ___Улучшение_жильяItem;
        
    }
    #endregion
    
    #region Поступление_в_приютItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/NadejdaAzureData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Поступление_в_приютItem :
        global::LightSwitchApplication.Поступление_в_приютItem.DetailsClass.IImplementation
    {
        partial void OnЛичный_номерChanged()
        {
            this.___OnPropertyChanged("Личный_номер");
            this.___OnPropertyChanged("Персональные_данныеItem");
        }
        
        partial void OnОбстоятельства_обусл_поступлениеChanged()
        {
            this.___OnPropertyChanged("Обстоятельства_обусл_поступление");
        }
        
        partial void OnРаспоряж_адм_номерChanged()
        {
            this.___OnPropertyChanged("Распоряж_адм_номер");
        }
        
        partial void OnРаспоряж_адм_датаChanged()
        {
            this.___OnPropertyChanged("Распоряж_адм_дата");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Поступление_в_приютItem.DetailsClass.IImplementation.Персональные_данныеItem
        {
            get
            {
                return this.Персональные_данныеItem;
            }
            set
            {
                this.Персональные_данныеItem = (global::LightSwitchApplication.Implementation.Персональные_данныеItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> __Персональные_данныеItem
        {
            get
            {
                if (this.___Персональные_данныеItem == null)
                {
                    this.___Персональные_данныеItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem>(
                        this,
                        "Персональные_данныеItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Персональные_данныеItem,
                        e => this._Персональные_данныеItem = e);
                }
                return this.___Персональные_данныеItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> ___Персональные_данныеItem;
        
    }
    #endregion
    
    #region Регистрация_ребенкаItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/NadejdaAzureData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Регистрация_ребенкаItem :
        global::LightSwitchApplication.Регистрация_ребенкаItem.DetailsClass.IImplementation
    {
        partial void OnЛичный_номерChanged()
        {
            this.___OnPropertyChanged("Личный_номер");
            this.___OnPropertyChanged("Персональные_данныеItem");
        }
        
        partial void OnДата_регистрации_по_месту_жительсваChanged()
        {
            this.___OnPropertyChanged("Дата_регистрации_по_месту_жительсва");
        }
        
        partial void OnАдрес_регистрации_по_месту_пребыванияChanged()
        {
            this.___OnPropertyChanged("Адрес_регистрации_по_месту_пребывания");
        }
        
        partial void OnСроки_регистрации_по_месту_пребывания_сChanged()
        {
            this.___OnPropertyChanged("Сроки_регистрации_по_месту_пребывания_с");
        }
        
        partial void OnСроки_регистрации_по_месту_пребывания_поChanged()
        {
            this.___OnPropertyChanged("Сроки_регистрации_по_месту_пребывания_по");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Регистрация_ребенкаItem.DetailsClass.IImplementation.Персональные_данныеItem
        {
            get
            {
                return this.Персональные_данныеItem;
            }
            set
            {
                this.Персональные_данныеItem = (global::LightSwitchApplication.Implementation.Персональные_данныеItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> __Персональные_данныеItem
        {
            get
            {
                if (this.___Персональные_данныеItem == null)
                {
                    this.___Персональные_данныеItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem>(
                        this,
                        "Персональные_данныеItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Персональные_данныеItem,
                        e => this._Персональные_данныеItem = e);
                }
                return this.___Персональные_данныеItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> ___Персональные_данныеItem;
        
    }
    #endregion
    
    #region Решение_СудаItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/NadejdaAzureData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Решение_СудаItem :
        global::LightSwitchApplication.Решение_СудаItem.DetailsClass.IImplementation
    {
        partial void OnCделаChanged()
        {
            this.___OnPropertyChanged("Cдела");
        }
        
        partial void OnДата_решения_судаChanged()
        {
            this.___OnPropertyChanged("Дата_решения_суда");
        }
        
        partial void OnПостановлениеChanged()
        {
            this.___OnPropertyChanged("Постановление");
        }
        
        partial void OnДата_постановленияChanged()
        {
            this.___OnPropertyChanged("Дата_постановления");
        }
        
        partial void OnНомер_постановленияChanged()
        {
            this.___OnPropertyChanged("Номер_постановления");
        }
        
    }
    #endregion
    
    #region РодителиItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/NadejdaAzureData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class РодителиItem :
        global::LightSwitchApplication.РодителиItem.DetailsClass.IImplementation
    {
        partial void OnCАдресChanged()
        {
            this.___OnPropertyChanged("CАдрес");
            this.___OnPropertyChanged("АдресItem");
        }
        
        partial void OnНомерсвChanged()
        {
            this.___OnPropertyChanged("Номерсв");
            this.___OnPropertyChanged("Свид_о_смертиItem");
        }
        
        partial void OnЛичный_номерChanged()
        {
            this.___OnPropertyChanged("Личный_номер");
        }
        
        partial void OnФИОChanged()
        {
            this.___OnPropertyChanged("ФИО");
        }
        
        partial void OnПолChanged()
        {
            this.___OnPropertyChanged("Пол");
        }
        
        partial void OnДата_рожденияChanged()
        {
            this.___OnPropertyChanged("Дата_рождения");
        }
        
        partial void OnЖив_мертвChanged()
        {
            this.___OnPropertyChanged("Жив_мертв");
        }
        
        partial void OnСтатус_отцаChanged()
        {
            this.___OnPropertyChanged("Статус_отца");
        }
        
        partial void OnCделаChanged()
        {
            this.___OnPropertyChanged("Cдела");
        }
        
        partial void OnАлименты_100рChanged()
        {
            this.___OnPropertyChanged("Алименты_100р");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.РодителиItem.DetailsClass.IImplementation.АдресItem
        {
            get
            {
                return this.АдресItem;
            }
            set
            {
                this.АдресItem = (global::LightSwitchApplication.Implementation.АдресItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.АдресItem> __АдресItem
        {
            get
            {
                if (this.___АдресItem == null)
                {
                    this.___АдресItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.АдресItem>(
                        this,
                        "АдресItem",
                        new string[] { "CАдрес" },
                        e => global::System.Object.Equals(e.Номер_Адрес, this.CАдрес),
                        () => this._АдресItem,
                        e => this._АдресItem = e);
                }
                return this.___АдресItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.АдресItem> ___АдресItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.РодителиItem.DetailsClass.IImplementation.Свид_о_смертиItem
        {
            get
            {
                return this.Свид_о_смертиItem;
            }
            set
            {
                this.Свид_о_смертиItem = (global::LightSwitchApplication.Implementation.Свид_о_смертиItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Свид_о_смертиItem> __Свид_о_смертиItem
        {
            get
            {
                if (this.___Свид_о_смертиItem == null)
                {
                    this.___Свид_о_смертиItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Свид_о_смертиItem>(
                        this,
                        "Свид_о_смертиItem",
                        new string[] { "Номерсв" },
                        e => global::System.Object.Equals(e.Номерсв, this.Номерсв),
                        () => this._Свид_о_смертиItem,
                        e => this._Свид_о_смертиItem = e);
                }
                return this.___Свид_о_смертиItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Свид_о_смертиItem> ___Свид_о_смертиItem;
        
    }
    #endregion
    
    #region Свид_о_смертиItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/NadejdaAzureData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Свид_о_смертиItem :
        global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.IImplementation
    {
        partial void OnНомерсвChanged()
        {
            this.___OnPropertyChanged("Номерсв");
        }
        
        partial void OnДата_смертиChanged()
        {
            this.___OnPropertyChanged("Дата_смерти");
        }
        
        partial void OnСвид_о_смерти_дата_выдачиChanged()
        {
            this.___OnPropertyChanged("Свид_о_смерти_дата_выдачи");
        }
        
        partial void OnСв_о_смерти_выданоChanged()
        {
            this.___OnPropertyChanged("Св_о_смерти_выдано");
        }
        
        partial void OnСерияChanged()
        {
            this.___OnPropertyChanged("Серия");
        }
        
        partial void OnНомерChanged()
        {
            this.___OnPropertyChanged("Номер");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Свид_о_смертиItem.DetailsClass.IImplementation.Родители
        {
            get
            {
                return this.Родители;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.РодителиItem> __Родители
        {
            get
            {
                if (this.___Родители == null)
                {
                    this.___Родители = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.РодителиItem>(
                        this,
                        "Родители",
                        () => this._Родители,
                        e => global::System.Object.Equals(e.Номерсв, this.Номерсв));
                }
                return this.___Родители;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.РодителиItem> ___Родители;
        
    }
    #endregion
    
    #region Тип_семьиItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/NadejdaAzureData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Тип_семьиItem :
        global::LightSwitchApplication.Тип_семьиItem.DetailsClass.IImplementation
    {
        partial void OnЛичный_номерChanged()
        {
            this.___OnPropertyChanged("Личный_номер");
            this.___OnPropertyChanged("Персональные_данныеItem");
        }
        
        partial void OnСтатус_семьиChanged()
        {
            this.___OnPropertyChanged("Статус_семьи");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Тип_семьиItem.DetailsClass.IImplementation.Персональные_данныеItem
        {
            get
            {
                return this.Персональные_данныеItem;
            }
            set
            {
                this.Персональные_данныеItem = (global::LightSwitchApplication.Implementation.Персональные_данныеItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> __Персональные_данныеItem
        {
            get
            {
                if (this.___Персональные_данныеItem == null)
                {
                    this.___Персональные_данныеItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem>(
                        this,
                        "Персональные_данныеItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Персональные_данныеItem,
                        e => this._Персональные_данныеItem = e);
                }
                return this.___Персональные_данныеItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> ___Персональные_данныеItem;
        
    }
    #endregion
    
    #region Улучшение_жильяItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/NadejdaAzureData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Улучшение_жильяItem :
        global::LightSwitchApplication.Улучшение_жильяItem.DetailsClass.IImplementation
    {
        partial void OnЛичный_номерChanged()
        {
            this.___OnPropertyChanged("Личный_номер");
            this.___OnPropertyChanged("Персональные_данныеItem");
        }
        
        partial void OnC_льготной_очереди_по_улучшению_жильяChanged()
        {
            this.___OnPropertyChanged("C_льготной_очереди_по_улучшению_жилья");
        }
        
        partial void OnДата_постановки_на_очередьChanged()
        {
            this.___OnPropertyChanged("Дата_постановки_на_очередь");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Улучшение_жильяItem.DetailsClass.IImplementation.Персональные_данныеItem
        {
            get
            {
                return this.Персональные_данныеItem;
            }
            set
            {
                this.Персональные_данныеItem = (global::LightSwitchApplication.Implementation.Персональные_данныеItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> __Персональные_данныеItem
        {
            get
            {
                if (this.___Персональные_данныеItem == null)
                {
                    this.___Персональные_данныеItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem>(
                        this,
                        "Персональные_данныеItem",
                        new string[] { "Личный_номер" },
                        e => global::System.Object.Equals(e.Личный_номер, this.Личный_номер),
                        () => this._Персональные_данныеItem,
                        e => this._Персональные_данныеItem = e);
                }
                return this.___Персональные_данныеItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Персональные_данныеItem> ___Персональные_данныеItem;
        
    }
    #endregion
    
    #region NadejdaAzureDataObjectContext
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class NadejdaAzureDataObjectContext
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.АдресItem))
            {
                return new global::LightSwitchApplication.Implementation.АдресItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Документы_ребенкаItem))
            {
                return new global::LightSwitchApplication.Implementation.Документы_ребенкаItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Жилье_ребенкаItem))
            {
                return new global::LightSwitchApplication.Implementation.Жилье_ребенкаItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Закрепленное_жильеItem))
            {
                return new global::LightSwitchApplication.Implementation.Закрепленное_жильеItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Паспортные_данныеItem))
            {
                return new global::LightSwitchApplication.Implementation.Паспортные_данныеItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ПенсияItem))
            {
                return new global::LightSwitchApplication.Implementation.ПенсияItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Персональные_данныеItem))
            {
                return new global::LightSwitchApplication.Implementation.Персональные_данныеItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Поступление_в_приютItem))
            {
                return new global::LightSwitchApplication.Implementation.Поступление_в_приютItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Регистрация_ребенкаItem))
            {
                return new global::LightSwitchApplication.Implementation.Регистрация_ребенкаItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Решение_СудаItem))
            {
                return new global::LightSwitchApplication.Implementation.Решение_СудаItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.РодителиItem))
            {
                return new global::LightSwitchApplication.Implementation.РодителиItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Свид_о_смертиItem))
            {
                return new global::LightSwitchApplication.Implementation.Свид_о_смертиItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Тип_семьиItem))
            {
                return new global::LightSwitchApplication.Implementation.Тип_семьиItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Улучшение_жильяItem))
            {
                return new global::LightSwitchApplication.Implementation.Улучшение_жильяItem();
            }
            return null;
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.NadejdaAzureData))
            {
                return new global::LightSwitchApplication.NadejdaAzureData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.NadejdaAzureData))
            {
                return new global::LightSwitchApplication.Implementation.NadejdaAzureDataObjectContext(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../NadejdaAzureData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.АдресItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.АдресItem);
            }
            if (typeof(global::LightSwitchApplication.Документы_ребенкаItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Документы_ребенкаItem);
            }
            if (typeof(global::LightSwitchApplication.Жилье_ребенкаItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Жилье_ребенкаItem);
            }
            if (typeof(global::LightSwitchApplication.Закрепленное_жильеItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Закрепленное_жильеItem);
            }
            if (typeof(global::LightSwitchApplication.Паспортные_данныеItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Паспортные_данныеItem);
            }
            if (typeof(global::LightSwitchApplication.ПенсияItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ПенсияItem);
            }
            if (typeof(global::LightSwitchApplication.Персональные_данныеItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Персональные_данныеItem);
            }
            if (typeof(global::LightSwitchApplication.Поступление_в_приютItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Поступление_в_приютItem);
            }
            if (typeof(global::LightSwitchApplication.Регистрация_ребенкаItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Регистрация_ребенкаItem);
            }
            if (typeof(global::LightSwitchApplication.Решение_СудаItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Решение_СудаItem);
            }
            if (typeof(global::LightSwitchApplication.РодителиItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.РодителиItem);
            }
            if (typeof(global::LightSwitchApplication.Свид_о_смертиItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Свид_о_смертиItem);
            }
            if (typeof(global::LightSwitchApplication.Тип_семьиItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Тип_семьиItem);
            }
            if (typeof(global::LightSwitchApplication.Улучшение_жильяItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Улучшение_жильяItem);
            }
            return null;
        }
    }
}
