//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Персональные_данныеItemDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private Персональные_данныеItemDetail(int Персональные_данныеItemЛичный_номер) : base("LightSwitchApplication:Персональные_данныеItemDetail")
        {
                this.Персональные_данныеItemЛичный_номер = Персональные_данныеItemЛичный_номер;
            global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static Персональные_данныеItemDetail CreateInstance(int Персональные_данныеItemЛичный_номер)
        {
            return new global::LightSwitchApplication.Персональные_данныеItemDetail(
                        Персональные_данныеItemЛичный_номер
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItemDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItemDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItemDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItemDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItemDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItemDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItemDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Персональные_данныеItem_Changed();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItem_Loaded(bool succeeded);

        partial void Персональные_данныеItemЛичный_номер_Changed();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Персональные_данныеItem Персональные_данныеItem
        {
            get
            {
                return global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySetProperties.Персональные_данныеItem);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItem_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Персональные_данныеItemЛичный_номер
        {
            get 
            {
                return global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySetProperties.Персональные_данныеItemЛичный_номер);
            }
            set
            {
                global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySetProperties.Персональные_данныеItemЛичный_номер, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItemЛичный_номер_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySet, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.CommandSet, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySetProperties.Персональные_данныеItem;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass>.Entry
                __Персональные_данныеItemDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.__Персональные_данныеItemDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.__Персональные_данныеItemDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.__Персональные_данныеItemDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.__Персональные_данныеItemDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.__Персональные_данныеItemDetail_InvokeCreated,
                    global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.__Персональные_данныеItemDetail_InvokeActivated,
                    global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.__Персональные_данныеItemDetail_InvokeSaveErrorEvent);
            private static void __Персональные_данныеItemDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.Персональные_данныеItemDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.Персональные_данныеItemDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __Персональные_данныеItemDetail_InvokeSavingEvent(global::LightSwitchApplication.Персональные_данныеItemDetail s)
            {
                bool handled = false;
                s.Персональные_данныеItemDetail_Saving(ref handled);
                return handled;
            }
            private static void __Персональные_данныеItemDetail_InvokeSavedEvent(global::LightSwitchApplication.Персональные_данныеItemDetail s)
            {
                s.Персональные_данныеItemDetail_Saved();
            }
            private static bool __Персональные_данныеItemDetail_InvokeClosingEvent(global::LightSwitchApplication.Персональные_данныеItemDetail s)
            {
                bool cancel = false;
                s.Персональные_данныеItemDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __Персональные_данныеItemDetail_InvokeCreated(global::LightSwitchApplication.Персональные_данныеItemDetail s)
            {
                s.Персональные_данныеItemDetail_Created();
            }
            private static void __Персональные_данныеItemDetail_InvokeActivated(global::LightSwitchApplication.Персональные_данныеItemDetail s)
            {
                s.Персональные_данныеItemDetail_Activated();
            }
            private static bool __Персональные_данныеItemDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.Персональные_данныеItemDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.Персональные_данныеItemDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Data _Персональные_данныеItem;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, int>.Data _Персональные_данныеItemЛичный_номер;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem> Персональные_данныеItem
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>)base.GetItem(global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySetProperties.Персональные_данныеItem);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, int> Персональные_данныеItemЛичный_номер
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, int>)base.GetItem(global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySetProperties.Персональные_данныеItemЛичный_номер);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Entry
                    Персональные_данныеItem = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Entry(
                        "Персональные_данныеItem",
                        global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySetProperties._Персональные_данныеItem_Stub,
                        global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySetProperties._Персональные_данныеItem_Validate,
                        global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySetProperties._Персональные_данныеItem_CreateQuery,
                        global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySetProperties._Персональные_данныеItem_OnValueChanged,
                        global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySetProperties._Персональные_данныеItem_OnLoaded);
                private static void _Персональные_данныеItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Data> c, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Персональные_данныеItem, sf);
                }
                private static void _Персональные_данныеItem_Validate(global::LightSwitchApplication.Персональные_данныеItemDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Персональные_данныеItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Персональные_данныеItem_CreateQuery(global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass d, object[] args)
                {
                    return null;
                }
                private static void _Персональные_данныеItem_OnValueChanged(global::LightSwitchApplication.Персональные_данныеItemDetail s)
                {
                    s.Персональные_данныеItem_Changed();
                }

                private static void _Персональные_данныеItem_OnLoaded(global::LightSwitchApplication.Персональные_данныеItemDetail s, bool succeeded)
                {
                    s.Персональные_данныеItem_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, int>.Entry
                    Персональные_данныеItemЛичный_номер = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, int>.Entry(
                        "Персональные_данныеItemЛичный_номер",
                        false,
                        global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySetProperties._Персональные_данныеItemЛичный_номер_Stub,
                        global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySetProperties._Персональные_данныеItemЛичный_номер_Validate,
                        global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass.PropertySetProperties._Персональные_данныеItemЛичный_номер_OnValueChanged);
                private static void _Персональные_данныеItemЛичный_номер_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.Персональные_данныеItemDetail, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass, int>.Data> c, global::LightSwitchApplication.Персональные_данныеItemDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Персональные_данныеItemЛичный_номер, sf);
                }
                private static void _Персональные_данныеItemЛичный_номер_Validate(global::LightSwitchApplication.Персональные_данныеItemDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Персональные_данныеItemЛичный_номер_Validate(r);
                }
                private static void _Персональные_данныеItemЛичный_номер_OnValueChanged(global::LightSwitchApplication.Персональные_данныеItemDetail s)
                {
                    s.Персональные_данныеItemЛичный_номер_Changed();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Персональные_данныеListDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.Персональные_данныеListDetail, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private Персональные_данныеListDetail() : base("LightSwitchApplication:Персональные_данныеListDetail")
        {
            global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static Персональные_данныеListDetail CreateInstance()
        {
            return new global::LightSwitchApplication.Персональные_данныеListDetail(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеListDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеListDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеListDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеListDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеListDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеListDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеListDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Персональные_данные_SelectionChanged();

        partial void Персональные_данные_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данные_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Персональные_данные visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Персональные_данныеItem> Персональные_данные
        {
            get
            {
                return global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.PropertySetProperties.Персональные_данные);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данные_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.Персональные_данныеListDetail, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.PropertySet, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.CommandSet, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.PropertySetProperties.Персональные_данные;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.Персональные_данныеListDetail, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass>.Entry
                __Персональные_данныеListDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.Персональные_данныеListDetail, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.__Персональные_данныеListDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.__Персональные_данныеListDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.__Персональные_данныеListDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.__Персональные_данныеListDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.__Персональные_данныеListDetail_InvokeCreated,
                    global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.__Персональные_данныеListDetail_InvokeActivated,
                    global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.__Персональные_данныеListDetail_InvokeSaveErrorEvent);
            private static void __Персональные_данныеListDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.Персональные_данныеListDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.Персональные_данныеListDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __Персональные_данныеListDetail_InvokeSavingEvent(global::LightSwitchApplication.Персональные_данныеListDetail s)
            {
                bool handled = false;
                s.Персональные_данныеListDetail_Saving(ref handled);
                return handled;
            }
            private static void __Персональные_данныеListDetail_InvokeSavedEvent(global::LightSwitchApplication.Персональные_данныеListDetail s)
            {
                s.Персональные_данныеListDetail_Saved();
            }
            private static bool __Персональные_данныеListDetail_InvokeClosingEvent(global::LightSwitchApplication.Персональные_данныеListDetail s)
            {
                bool cancel = false;
                s.Персональные_данныеListDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __Персональные_данныеListDetail_InvokeCreated(global::LightSwitchApplication.Персональные_данныеListDetail s)
            {
                s.Персональные_данныеListDetail_Created();
            }
            private static void __Персональные_данныеListDetail_InvokeActivated(global::LightSwitchApplication.Персональные_данныеListDetail s)
            {
                s.Персональные_данныеListDetail_Activated();
            }
            private static bool __Персональные_данныеListDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.Персональные_данныеListDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.Персональные_данныеListDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable Персональные_данныеQuery()
            {
                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                        global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                            global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                                global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                                    global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                                        global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                                            global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                                                global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                                                    this.Screen.DataWorkspace.NadejdaAzureData.Персональные_данные,
                                                    "Документы_ребенкаItem"),
                                                "Жилье_ребенкаItem"),
                                            "Закрепленное_жильеItem"),
                                        "Паспортные_данныеItem"),
                                    "ПенсияItem"),
                                "Поступление_в_приютItem"),
                            "Регистрация_ребенкаItem"),
                        "Тип_семьиItem"),
                    "Улучшение_жильяItem");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Персональные_данныеListDetail, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Data _Персональные_данные;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.Персональные_данныеListDetail, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Персональные_данныеListDetail, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem> Персональные_данные
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Персональные_данныеListDetail, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>)base.GetItem(global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.PropertySetProperties.Персональные_данные);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.Персональные_данныеListDetail, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.Персональные_данныеListDetail, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Персональные_данныеListDetail, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Entry
                    Персональные_данные = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Персональные_данныеListDetail, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Entry(
                        "Персональные_данные",
                        global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.PropertySetProperties._Персональные_данные_Stub,
                        global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.PropertySetProperties._Персональные_данные_Validate,
                        global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.PropertySetProperties._Персональные_данные_CreateQuery,
                        global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.PropertySetProperties._Персональные_данные_SelectionChanged,
                        global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.PropertySetProperties._Персональные_данные_OnCollectionChanged,
                        global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass.PropertySetProperties._Персональные_данные_OnLoaded);
                private static void _Персональные_данные_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.Персональные_данныеListDetail, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Data> c, global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Персональные_данные, sf);
                }
                private static void _Персональные_данные_Validate(global::LightSwitchApplication.Персональные_данныеListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Персональные_данные_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Персональные_данные_CreateQuery(global::LightSwitchApplication.Персональные_данныеListDetail.DetailsClass d, object[] args)
                {
                    return d.Персональные_данныеQuery();
                }
                private static void _Персональные_данные_SelectionChanged(global::LightSwitchApplication.Персональные_данныеListDetail s)
                {
                    s.Персональные_данные_SelectionChanged();
                }
                private static void _Персональные_данные_OnCollectionChanged(global::LightSwitchApplication.Персональные_данныеListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Персональные_данные_Changed(e);
                }
                private static void _Персональные_данные_OnLoaded(global::LightSwitchApplication.Персональные_данныеListDetail s, bool succeeded)
                {
                    s.Персональные_данные_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class CreateNewПерсональные_данныеItem
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.CreateNewПерсональные_данныеItem, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private CreateNewПерсональные_данныеItem() : base("LightSwitchApplication:CreateNewПерсональные_данныеItem")
        {
            global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static CreateNewПерсональные_данныеItem CreateInstance()
        {
            return new global::LightSwitchApplication.CreateNewПерсональные_данныеItem(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewПерсональные_данныеItem_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewПерсональные_данныеItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewПерсональные_данныеItem_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewПерсональные_данныеItem_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewПерсональные_данныеItem_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewПерсональные_данныеItem_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewПерсональные_данныеItem_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Персональные_данныеItemProperty_Changed();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Персональные_данныеItem Персональные_данныеItemProperty
        {
            get 
            {
                return global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.PropertySetProperties.Персональные_данныеItemProperty);
            }
            set
            {
                global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.SetValue(this, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.PropertySetProperties.Персональные_данныеItemProperty, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Персональные_данныеItemProperty_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewПерсональные_данныеItem, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.PropertySet, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.CommandSet, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.PropertySetProperties.Персональные_данныеItemProperty;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewПерсональные_данныеItem, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass>.Entry
                __CreateNewПерсональные_данныеItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewПерсональные_данныеItem, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.__CreateNewПерсональные_данныеItem_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.__CreateNewПерсональные_данныеItem_InvokeSavingEvent,
                    global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.__CreateNewПерсональные_данныеItem_InvokeSavedEvent,
                    global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.__CreateNewПерсональные_данныеItem_InvokeClosingEvent,
                    global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.__CreateNewПерсональные_данныеItem_InvokeCreated,
                    global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.__CreateNewПерсональные_данныеItem_InvokeActivated,
                    global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.__CreateNewПерсональные_данныеItem_InvokeSaveErrorEvent);
            private static void __CreateNewПерсональные_данныеItem_InvokeInitializeDataWorkspace(global::LightSwitchApplication.CreateNewПерсональные_данныеItem s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.CreateNewПерсональные_данныеItem_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __CreateNewПерсональные_данныеItem_InvokeSavingEvent(global::LightSwitchApplication.CreateNewПерсональные_данныеItem s)
            {
                bool handled = false;
                s.CreateNewПерсональные_данныеItem_Saving(ref handled);
                return handled;
            }
            private static void __CreateNewПерсональные_данныеItem_InvokeSavedEvent(global::LightSwitchApplication.CreateNewПерсональные_данныеItem s)
            {
                s.CreateNewПерсональные_данныеItem_Saved();
            }
            private static bool __CreateNewПерсональные_данныеItem_InvokeClosingEvent(global::LightSwitchApplication.CreateNewПерсональные_данныеItem s)
            {
                bool cancel = false;
                s.CreateNewПерсональные_данныеItem_Closing(ref cancel);
                return cancel;
            }
            private static void __CreateNewПерсональные_данныеItem_InvokeCreated(global::LightSwitchApplication.CreateNewПерсональные_данныеItem s)
            {
                s.CreateNewПерсональные_данныеItem_Created();
            }
            private static void __CreateNewПерсональные_данныеItem_InvokeActivated(global::LightSwitchApplication.CreateNewПерсональные_данныеItem s)
            {
                s.CreateNewПерсональные_данныеItem_Activated();
            }
            private static bool __CreateNewПерсональные_данныеItem_InvokeSaveErrorEvent(global::LightSwitchApplication.CreateNewПерсональные_данныеItem s, global::System.Exception ex)
            {
                bool handled = false;
                s.CreateNewПерсональные_данныеItem_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewПерсональные_данныеItem, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Data _Персональные_данныеItemProperty;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.CreateNewПерсональные_данныеItem, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewПерсональные_данныеItem, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem> Персональные_данныеItemProperty
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewПерсональные_данныеItem, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>)base.GetItem(global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.PropertySetProperties.Персональные_данныеItemProperty);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.CreateNewПерсональные_данныеItem, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.CreateNewПерсональные_данныеItem, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewПерсональные_данныеItem, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Entry
                    Персональные_данныеItemProperty = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewПерсональные_данныеItem, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Entry(
                        "Персональные_данныеItemProperty",
                        false,
                        global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.PropertySetProperties._Персональные_данныеItemProperty_Stub,
                        global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.PropertySetProperties._Персональные_данныеItemProperty_Validate,
                        global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass.PropertySetProperties._Персональные_данныеItemProperty_OnValueChanged);
                private static void _Персональные_данныеItemProperty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewПерсональные_данныеItem, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass, global::LightSwitchApplication.Персональные_данныеItem>.Data> c, global::LightSwitchApplication.CreateNewПерсональные_данныеItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Персональные_данныеItemProperty, sf);
                }
                private static void _Персональные_данныеItemProperty_Validate(global::LightSwitchApplication.CreateNewПерсональные_данныеItem s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Персональные_данныеItemProperty_Validate(r);
                }
                private static void _Персональные_данныеItemProperty_OnValueChanged(global::LightSwitchApplication.CreateNewПерсональные_данныеItem s)
                {
                    s.Персональные_данныеItemProperty_Changed();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
